wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1667650389.719359
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
amp:
  desc: null
  value: 0.7
bat_count:
  desc: null
  value: 10
epochs:
  desc: null
  value: 1000
freq:
  desc: null
  value: 0.5
freq_max:
  desc: null
  value: 1
freq_min:
  desc: null
  value: 0
network:
  desc: null
  value:
  - 3
  - 2
type:
  desc: null
  value: BA
